spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product,/api/product/{id},/api/product/add
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
