spring:
  application:
    name: inventory-service
  h2:
    console:
      enabled: 'true'
      path: /h2
  datasource:
    username: sa
    password: ''
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}