spring:
  application:
    name: product-service
  h2:
    console:
      enabled: 'true'
      path: /h2
  datasource:
    username: sa
    password: ''
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  cache:
    cache-names: getProduct, getAllProducts
    caffeine:
      spec: maximumSize=500, expireAfterAccess=300s
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
